name: CIFuzz
on:
  push:
    branches:
      - master
  
      
  pull_request:
    branches:
      - master
    
jobs:
  build:

    runs-on: ubuntu-latest    
     
    steps:
    
      - uses: actions/checkout@v2
        name: Check out code
        
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: khushi2/oss-fuzz
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  Fuzzing:
   runs-on: ubuntu-latest
   concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
   
   strategy:
        fail-fast: false
        matrix:
            sanitizer: 
              - address
            engine:
               - afl
            architecture:
              - x86_64
            
   env:
      ENGINE: ${{ matrix.engine }}
      SANITIZER: ${{ matrix.sanitizer }}
      ARCHITECTURE: ${{ matrix.architecture }}
      
   
   steps:
     - uses: actions/checkout@v3        
        
     - name: Compile and Run Fuzzers (${{ matrix.sanitizer }})
       uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
       with:
        ENGINE: ${{ matrix.engine }}
        github-token: ${{ secrets.TOKEN }}
        sanitizer: ${{ matrix.sanitizer }}
        language: c
        fuzz-seconds: 200
        dry-run: false
        report-unreproducible-crashes: true
        keep-unaffected-fuzz-targets: true
        
        
         
        
  
       
        
        
        
